id: A3AD4A4EA
title: A Brief Practice of Consecrating Amṛta for the Vidyādhara Assembly
type: translation
pechas:
- I13CAEA4E
- IE99E0CDC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:34:51.555577
  last_modified_at: 2023-01-04 12:34:51.555590
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I13CAEA4E/A721: 68A4
  IE99E0CDC/79D5: 68A4
